import { Level, TileType } from './types'

const T = TileType

export const levels: Level[] = [
  {
    name: '第1关 - 初次见面',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第2关 - 水火初遇',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.GROUND, T.WATER, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第3关 - 第一道门',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第4关 - 双人开门',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.GROUND, T.GROUND, T.LAVA, T.ICE_GEM, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.DOOR, T.DOOR, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 12, y: 1 },
    totalFireGems: 2,
    totalIceGems: 2
  },
  {
    name: '第5关 - 冰火迷宫',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_GEM, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.ICE_GEM, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 3,
    totalIceGems: 3
  },
  {
    name: '第6关 - 狭长通道',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.FIRE_PORTAL, T.WALL, T.WALL, T.ICE_PORTAL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 12, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第7关 - 水中取宝',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.WATER, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 11, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第8关 - 岩浆漫步',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.LAVA, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 11, y: 1 },
    iceStart: { x: 1, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第9关 - 交错之路',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.DOOR, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 9, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第10关 - 双子宝石',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.ICE_GEM, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.DOOR, T.DOOR, T.DOOR, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 2,
    totalIceGems: 2
  },
  {
    name: '第11关 - 迂回战术',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.PRESSURE_PLATE, T.DOOR, T.DOOR, T.PRESSURE_PLATE, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第12关 - 三岔路口',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WALL, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第13关 - 步步为营',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.DOOR, T.DOOR, T.DOOR, T.DOOR, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.FIRE_GEM, T.WALL, T.DOOR, T.GROUND, T.GROUND, T.DOOR, T.WALL, T.ICE_GEM, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.DOOR, T.GROUND, T.GROUND, T.DOOR, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 12, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第14关 - 冰火两重天',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.WATER, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.DOOR, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.WATER, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 4,
    totalIceGems: 4
  },
  {
    name: '第15关 - 孤岛求生',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.GROUND, T.FIRE_GEM, T.GROUND, T.ICE_GEM, T.GROUND, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WATER, T.WATER, T.WATER, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.WATER, T.WATER, T.WATER, T.WALL],
      [T.WALL, T.WATER, T.FIRE_GEM, T.WATER, T.LAVA, T.GROUND, T.PRESSURE_PLATE, T.DOOR, T.PRESSURE_PLATE, T.GROUND, T.LAVA, T.WATER, T.ICE_GEM, T.WATER, T.WALL],
      [T.WALL, T.WATER, T.WATER, T.WATER, T.LAVA, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.LAVA, T.WATER, T.WATER, T.WATER, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 3,
    totalIceGems: 3
  },
  {
    name: '第16关 - 蛇形通道',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.FIRE_GEM, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.DOOR, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.DOOR, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 12, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第17关 - 中心宝石',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.PRESSURE_PLATE, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WALL],
      [T.WALL, T.LAVA, T.FIRE_GEM, T.LAVA, T.LAVA, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WALL],
      [T.WALL, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WATER, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 11, y: 1 },
    totalFireGems: 2,
    totalIceGems: 2
  },
  {
    name: '第18关 - 双重机关',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WALL, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.WALL, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.GROUND, T.WALL, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.WALL, T.GROUND, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '第19关 - 终极试炼',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.WATER, T.WATER, T.WATER, T.WATER, T.DOOR, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_GEM, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.ICE_GEM, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.WATER, T.WATER, T.WATER, T.WATER, T.DOOR, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 5,
    totalIceGems: 5
  },
  {
    name: '第20关 - 森林大冒险',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.DOOR, T.DOOR, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.DOOR, T.DOOR, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.DOOR, T.DOOR, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 15, y: 1 },
    totalFireGems: 5,
    totalIceGems: 5
  }
]
