import { Level, TileType } from './types'

const T = TileType

export const levels: Level[] = [
  {
    name: '新手教程',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '水火不容',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 2,
    totalIceGems: 1
  },
  {
    name: '机关重重',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.ICE_GEM, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 10, y: 1 },
    totalFireGems: 1,
    totalIceGems: 1
  },
  {
    name: '协同合作',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.GROUND, T.GROUND, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.FIRE_GEM, T.GROUND, T.WATER, T.FIRE_GEM, T.GROUND, T.GROUND, T.LAVA, T.ICE_GEM, T.GROUND, T.ICE_GEM, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.WATER, T.WATER, T.DOOR, T.DOOR, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 12, y: 1 },
    totalFireGems: 2,
    totalIceGems: 2
  },
  {
    name: '终极挑战',
    map: [
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.FIRE_GEM, T.WATER, T.GROUND, T.LAVA, T.ICE_GEM, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_GEM, T.GROUND, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.PRESSURE_PLATE, T.GROUND, T.GROUND, T.ICE_GEM, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.DOOR, T.DOOR, T.DOOR, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.WATER, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.LAVA, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.GROUND, T.GROUND, T.WATER, T.FIRE_GEM, T.WATER, T.WATER, T.GROUND, T.LAVA, T.LAVA, T.ICE_GEM, T.LAVA, T.GROUND, T.GROUND, T.WALL],
      [T.WALL, T.FIRE_PORTAL, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.GROUND, T.ICE_PORTAL, T.WALL],
      [T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL, T.WALL]
    ],
    fireStart: { x: 1, y: 1 },
    iceStart: { x: 13, y: 1 },
    totalFireGems: 3,
    totalIceGems: 3
  }
]
